config/routes.rb
Crackphysics::Application.routes.draw do

  get 'purchases/pay' => 'purchases#pay' , :as => 'purchases'
  get 'purchases/afterpay' => 'purchases#afterpay' , :as => 'after_purchases'
  get 'exams/index' => 'exam#index' , :as => 'examitems'
  get 'test_items/restart' => 'test_items#restart' , :as => 'restart_test_item'
  get 'test_items/delete' => 'test_items#delete' , :as => 'delete_test_item'
  get 'test_items/index' => 'test_items#index' , :as => 'testitems'
  get 'test_items/new' => 'test_items#new', :as => 'new_test_item'
  get 'test_items/get_testitem_details' => 'test_items#get_testitem_details', :as => 'get_testitme_details'
  get 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  put 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  get 'test_supervisor/loop' => 'test_supervisor#loop' , :as => 'testloop'
  get 'report/list_tests' => 'report#list_tests' , :as => 'showtests'
  get 'report/show_units_bar_chart' => 'report#show_units_bar_chart' , :as => 'showunitsbarchart'
  get 'report/show_tests_line_chart' => 'report#show_tests_line_chart' , :as => 'showtestslinechart'
  get 'report/print_test' => 'report#print_test' , :as => 'printtestpdf'
  get 'question_statements/showf' => 'question_statements#showf' , :as => 'getquestion'
  get 'test_factory/create_unit_test' => 'test_factory#create_unit_test', :as => 'createunittest' 
  get 'unit/index' => 'unit#index' , :as => 'unititems'
  get 'unit/indexdd' => 'unit#indexdd', :as => 'unitslist' 
  get 'unit/indexnottaken' => 'unit#indexnottaken', :as => 'unitsnottakenlist' 
  get 'unit/show/:id' => 'unit#show' , :as => 'unit'
  get 'user/welcome' => 'user#welcome', :as => 'welcome' 
  get 'main/start' => 'main#start', :as => 'home' 
  get 'how_to_upgrade' => 'main#how_to_upgrade', :as => 'upgrade' 
  post 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/show' => 'user#show', :as => 'usershow' 
  post 'user/signup' => 'user#signup', :as => 'usersignup' 
  post 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  get 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  put 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/logout' => 'user#logout', :as => 'userlogout' 
  get 'user/signup' => 'user#signup', :as => 'usersignup'
  get 'exam/get_test_types/:exam_id/:format' => 'exam#get_test_types'
  get 'exam/get_units/:exam_id/:format' => 'exam#get_units'
  get 'help' => 'main#show_help' , :as => 'help' 
  get 'feedback' => 'feedbacks#new', :as => 'feedback'
  post 'feedback/create' => 'feedbacks#create', :as => 'feedbackcreate'
  get 'subscription/index' => 'subscription#index', :as => 'subscriptionindex' 

  root :to => "main#start"

  mount PaypalIpn, :at => '/paypal_ipn' 
end

app/models/test_item.rb
class TestItem < ActiveRecord::Base
  has_many :test_questions
  def strike_ratio 
     read_attribute(:correct_count).to_f / read_attribute(:question_count)
  end
  def corr_vs_incorr
    type = TestType.find_by_id( read_attribute(:test_type_id) )
    "Corr/Total=" + read_attribute(:correct_count).to_s + "/" + read_attribute(:question_count).to_s
  end 
  def test_xstr
    taken_on = read_attribute(:created_on)
    taken_on.to_s(:short) 
  end
  def test_lbl
    "Test"
  end 
  def google_chart_data_str
   created_on = read_attribute(:created_on)
   datestr = created_on.strftime("%Y,")+(created_on.mon-1).to_s+created_on.strftime(",%d,%H,%M")
   return "[new Date(" + datestr + ")," +strike_ratio.to_s + ", null]"
  end
end

app/controllers/test_items_controller.rb
class TestItemsController < ApplicationController
  before_filter :login_required
  before_filter :can_show_list?#, :only => [:new,:delete,:update]
  def index
   @AllTests = (TestType.find(:all)).map{ |t| t.name }
   user_id = session[:user].id
   @unfinished = TestItem.where(:status=>'new',:user_id=>user_id)
   @user = User.find_by_id(user_id)
   sleep(5)
   @totaltests = TestItem.where(:user_id => user_id , :status => 'submit').length
   if  @totaltests >= 2 then
    @unfinished = [] 
   end
  end
  def restart
    testitem_id = params[:id].to_i
    session[:test_id] = testitem_id
    @q =  TestQuestion.where(:test_item_id=>testitem_id).first
    session[:curr_qid] = @q.id
    redirect_to :action => "update", :page => "1",:layout=>true
  end
  def delete
    testitem_id = params[:id].to_i
    testitem = TestItem.where(:id => testitem_id ).first
    testitem.status = 'delete'
    testitem.save 
    redirect_to :action => 'get_testitem_details'
  end 
  def get_testitem_details
   user_id = session[:user].id
   exam_ids = Subscription.where(:user_id=>user_id).collect { |s| s.exam_id }
   @exams = Exam.where(:id=>exam_ids) 
   @unfinished = TestItem.where(:status=>'new',:user_id=>user_id)
  end
  def new
    required_params = ["exam_id","test_item_id","numofqs"]
    redirect_to :action => :get_testitem_details and return unless (required_params - params.keys).empty? 
    testitem = params[:test_item_id]
    num_of_qs = params[:numofqs].to_i
    testitem = TestType.find(testitem)
    logger.debug testitem.code
    case testitem.code
    when 'unit'
      unit = params[:unit]
      create_unit_test(unit,num_of_qs)
      logger.debug "===> Created unit test <====" 
    when 'full'
      create_full_test(num_of_qs)
      logger.debug "===> Created full test <====" 
    when 'progressivetest'
      unit = params[:unit]
      create_progressive_test(num_of_qs,unit)
      logger.debug "===> Created progressive test <====" 
    end 
    logger.debug "===> Finished creating test <====== #{testitem=='progressive'}" 
    redirect_to :action => "update", :page => "1",:layout=>true
  end
  
  def update
    logger.debug session.inspect
    currtest = TestItem.find_by_id(session[:test_id])
    q = TestQuestion.find_by_id(session[:curr_qid])
    q.current_choice = params[:answers_buttons].to_i if params[:answers_buttons]
    q.current_choice = params[:currchoice].to_i if params[:currchoice]
    q.save
    if params[:save] # if test is submitted
      currtest.status = 'submit'
      questions = TestQuestion.find_all_by_test_item_id(session[:test_id])
      currtest.correct_count = (questions.find_all{ |q| q.current_choice == q.correct_choice}).length 
      currtest.save
      testtypeid = currtest.test_type_id
      testname = TestType.find_by_id(testtypeid).code
      logger.debug "The test name is **********#{testname}****************"
      case testname 
      when 'unit', 'progressive'
        #user_id = session[:user].id
        #u = User.find_by_id(user_id)
        #unitssoffar = u.units_attempted
        #logger.debug "New unitid"
        #unitssoffar << session[:curr_unit]
        #logger.debug unitssoffar
        #u.units_attempted = unitssoffar.uniq
        #u.save
      end 
      session[:test_id] = nil
      redirect_to home_path
    elsif params[:cancel] # if cancel delete it
      currtest.delete
      session[:test_id] = nil
      redirect_to home_path
    else # else call update again
      questions = TestQuestion.find_all_by_test_item_id(session[:test_id],:order => 'id')
      logger.debug questions.inspect
      i = params[:page].to_i - 1
      @q = questions[i] 
      @qs = QuestionStatement.where( :id => @q.question_statement_id  ).first 
      #@question = currtest.get_question_at params[:page]
      @qrange = Array.new( questions.length ){|i| i+1}
      @unanscount = ( questions.find_all { |q| q.current_choice == 0 } ).length
      session[:curr_qid] = @q.id
      render(:layout => false) unless params[:layout] 
    end
  end
   
  def create_n_questions(qstmt_ids,testid)
   qstmt_ids.each { |id|
     qs = QuestionStatement.find_by_id(id)
     logger.debug "===>Choices are #{qs.choices}<==="
     shuffledchoices = shuffle( Array.new(qs.choices.length){|i| i+1} )
     logger.debug "===>Shuffled choices are #{shuffledchoices}<==="
     q = TestQuestion.create({:test_item_id=>testid,:question_statement_id=>id,:current_choice=>0,:answer_sequence=>shuffledchoices})
     correct_choice = q.mapindex( qs.correct_choice_index )
     q.correct_choice = correct_choice
     q.save
   }
  end
# create unit test
  def create_unit_test(unit,num_of_qs)
    user_id = session[:user].id
    qstmt_ids = get_n_questions_from_catid(unit,num_of_qs)
    testtypeid = TestType.where(:code=>'unit').first.id
    TestItem.transaction do 
      testitem = TestItem.create({:user_id=>user_id,:test_type_id=>testtypeid,:question_count=>num_of_qs})
      create_n_questions(qstmt_ids,testitem.id)
      session[:test_id] = testitem.id
      @q =  TestQuestion.where(:test_item_id=>testitem.id).first
      session[:curr_qid] = @q.id
      session[:curr_unit] = unit.to_i
    end
  end
 def can_show_list?
   retval = true 
   user_id = session[:user].id
   @user = User.find_by_id(user_id)
   @totaltests = TestItem.where(:user_id => user_id , :status => 'submit').length
   if  @totaltests >= 2 then
     retval = false
   end
   return retval
 end 
# create full test
  def create_full_test(total_questions)
   qstmts = QuestionStatement.find(:all,:limit => total_questions,:order=>get_order_by)
   user_id = session[:user].id
   qstmts = qstmts.uniq
   qstmt_ids = qstmts.collect { |c| c.id } 
   testtypeid = TestType.where(:code=>'full').first.id
   TestItem.transaction do 
      testitem = TestItem.create({:user_id=>user_id,:test_type_id=>testtypeid,:question_count=>total_questions})
      create_n_questions(qstmt_ids,testitem.id)
      session[:test_id] = testitem.id
      @q =  TestQuestion.where(:test_item_id=>testitem.id).first
      session[:curr_qid] = @q.id
    end
  end
  def get_order_by
   orderby = "RANDOM()"
   ismysql = ActiveRecord::Base.connection.instance_values["config"][:adapter].index("mysql")
   orderby = "RAND()" if ismysql
   return orderby
  end
# create progressive test
  def create_progressive_test(total_questions,unit)
   logger.debug "==> Making progressive test..New unit is #{unit}...Total Questions are #{total_questions}"
   total_questions = total_questions.to_i
   unit = unit.to_i
   units = (User.find_by_id(session[:user].id).units_attempted << unit).find_all { |u| u != nil }
   qstmt_ids = []
   qsperunit = total_questions / units.length
   qsperunit = 1 if qsperunit == 0 
   logger.debug "Units attempted = #{units.inspect} Questions per unit are #{qsperunit}"
   units.each { |unit_id|
    qstmt_ids = qstmt_ids + get_n_questions_from_catid(qsperunit,unit_id)
   }
   # fill rest from current test
   qstmt_ids = qstmt_ids +  get_n_questions_from_catid(total_questions - qstmt_ids.length , unit )
   logger.debug "Question statements ids-> #{qstmt_ids.inspect}"
   user_id = session[:user].id
   testtypeid = TestType.where(:code=>'progressive').first.id
   TestItem.transaction do 
      testitem = TestItem.create({:user_id=>user_id,:test_type_id=>testtypeid,:question_count=>total_questions})
      create_n_questions(qstmt_ids,testitem.id)
      session[:test_id] = testitem.id
      @q =  TestQuestion.where(:test_item_id=>testitem.id).first
      session[:curr_qid] = @q.id
      session[:curr_unit] = unit
    end
    end
  end
##########################################
#helper functions
  def get_n_questions(total_questions)
    qstmt_ids = []
    concepts=UnderlyingConcept.find(:all,:select=>"question_statement_id",:limit=>total_questions,:order=>get_order_by)
    logger.info concepts
    qstmt_ids = concepts.collect { |c| c.question_statement_id } 
    return qstmt_ids.uniq
  end
  def get_n_questions_from_catid(cat_id,total_questions)
    qstmt_ids = []
    user_id = session[:user].id
    exam_id = Subscription.find_by_user_id(user_id,:select=>"exam_id").exam_id
    concepts=UnderlyingConcept.find_all_by_unit_id_and_exam_id(cat_id ,exam_id ,:select=>"question_statement_id",:limit=>total_questions,:order=>get_order_by)
    logger.info concepts
    qstmt_ids = concepts.collect { |c| c.question_statement_id } 
    return qstmt_ids.uniq
  end
  def shuffle(arr)
   logger.debug "===>Arr #{arr}<==="
   logger.debug "===Shuffled arr #{arr.sort{rand-0.5}}<==="
   return  arr.sort { rand-0.5 }
  end 
###########################################

app/views/test_items/_currentquestion.html.erb
<%logger.debug @q.inspect %>
<%logger.debug @qs.inspect %>
<div id="QuestionStatement">
  <%= raw @qs.statement  %>
  <%= image_tag "http://arth-tantr.com/images_cp/#{@qs.image_loc}",:class => "question_image"  if @qs.image_loc && @qs.image_loc.size > 2 %>
</div>
<div id="AnswerStatements"> 
  <table class='ansstmts'>
    <tr>
      <th class='ansindex'></th>
      <th class='ansstmt'></th>
      <th class='anscheck'></th>
    </tr>
    <% i=1 %>
    <% choices = @qs.choices %>
    <% @q.answer_sequence.each do |answer| %>
    <tr>
    <td>
      <%= i %>)
    </td>
    <td align='left' >
      <%= raw choices[answer-1] %>
    </td>
    <td>
      <input type="radio" id="answer_pos" class='answer_buttons' name="answers_buttons" value="<%=i%>" <% if @q.current_choice == i %> checked <% end%> > </input>
    </td>
    </tr>
    <% i = i +1 %> 
    <%end%>
  </table>
</div>

app/views/test_items/_paginate.html.erb
<div id='PagiBar'>
  <% currpage = params[:page].to_i %>
  <% if currpage > 1 then %>
  <a href='#' onclick='updateAndSubmit(<%= currpage-1 %>)' class='pagilinks' id='PrevNextQLink'> < </a>
  <%end%> 
  <% @qrange.each do |qnum| %>
    <% if qnum == currpage then%>
      <span id='CurrQLink'> <%= qnum %> </span>
    <% else %>
      <a href='#' onclick='updateAndSubmit(<%= qnum %>)' class='pagilinks'> <%= qnum %> </a>
    <%end%> 
  <%end%> 
  <% if currpage < @qrange.length then %>
  <a href='#' onclick='updateAndSubmit(<%= currpage+1 %>)' class='pagilinks' id='PrevNextQLink'> > </a>
  <%end%> 
</div>

app/views/test_items/get_testitem_details.html.erb
<script type="text/javascript">
/*
jQuery(document).ready(function($){
    $("body").ajaxStart(function(){
         $(this).addClass("loading"); 
     });
    $("body").ajaxStop(function(){
         $(this).addClass("loading"); 
     });
    $("#exam_drop_down").select(function(){
    alert("Exam select");
   }); 
}); */
/* on load get the test types for given exam */
document.observe('dom:loaded',function(){
    updateTestItems();
    $("exam_drop_down").observe('select',updateTestItems);
});
function updateTestItems(){
  var exam_id = $('exam_drop_down')[$('exam_drop_down').selectedIndex].value; 
  $("units_tbl").hide();
  new Ajax.Updater('test_type','/exam/get_test_types/'+exam_id+"/nolayout",{asynchronous:true,method:'get',onComplete: function(response){
      var test_item = $("test_item_ids")
      var name = test_item[test_item.selectedIndex].text;
      var val = test_item.value;
      test_selected(name,val);
      $("test_item_ids").observe('change',
        function(event){
          test_selected( this[this.selectedIndex].text,this.value );
        }); 
      }});
};
function add_submit(TestName)
{
  var remote_func_name = 'new';
  switch(TestName)
  {
     case "Unit test": 
      $('test_item_ids').value = 'unittest';
      break;
     case "Full test": 
      $('test_item_ids').value = 'fulltest';
      break;/* Will do in ver 2.0
     case "Progressive test": 
      $('test_item_ids').value = 'progressivetest';
      break; */
     default:
      break; 
  };
  $('newtestform').writeAttribute('action',remote_func_name);
  var submit_attrs = { id: 'submittest' , value : 'Start  test', type: 'submit' };
  var submittest = new Element('input',submit_attrs);
  $('newtest_submit').insert(submittest);
  return false;
}
function confirmDelete()
{
  var retval = false ;
  retval = confirm("Confirm delete!"); 
  return retval ;

};
function insertUnits(UnitsPlaceHolder,currentunit,TestName)
{ 
  if( undefined != currentunit )
  {
    $(UnitsPlaceHolder).insert(currentunit);
  }
  add_submit(TestName); 
};
function test_selected(TestName,TestId)
 {
  if( undefined != $('currentunit') )
  {
    $('currentunit').remove();
  }
  if( undefined != $('submittest') )
  {
    $('submittest').remove();
  }
  var currentunit = undefined; 
  var functocall = "add_submit('"+TestName+"')";
  var retval = false;
  switch(TestName)
  {
     case "Unit test": 
      var currunit_attrs = { id : 'currentunit' };
      var currentunit = new Element('span',currunit_attrs);
      var url = '/exam/get_units/'+TestId+'/nolayout';
      new Ajax.Updater('currentunit',url,{asynchronous:true,method:'get',onComplete:eval("insertUnits")("units_ph",currentunit,TestName)});
      $("units_tbl").show();
      break;
    case "Full test":
      numqs = $('numofqs').value;
      add_submit(TestName);
      retval = true;
      $("units_tbl").hide();
      break; 
    case "Progressive test": 
      var currunit_attrs = { id : 'currentunit' };
      var currentunit = new Element('span',currunit_attrs);
      new Ajax.Updater('currentunit','/exam/get_unattempted_units/'+TestId+'/nolayout',{asynchronous:true,method:'get',onComplete:eval("insertUnits")("units_ph",currentunit,TestName)});
      $("units_tbl").show();
      break;
     default:
      break; 
  };
  return retval;
 };
</script>
<% if @unfinished.length > 0 %> 
<div id='UnsavedTests' class='centered' style="width:60%;padding-bottom:30px;">
  <table> <caption> <h3>Restart previous test</h3> </caption>
  <% count = 1 %>
  <% @unfinished.each do |t| %>
    <% testtype = TestType.where( :id => t.test_type_id ).first.name %>
    <% tid = t.id %>
    <tr> 
      <th><%= testtype  %> </th> 
      <td> <i> started at <%= t.created_on %> </i> </td> 
      <td style="padding-left:5px;"> <a href="restart?id=<%=tid%>" > Continue  </a> </td>
      <td style="padding-left:5px;"> <a href="delete?id=<%=tid%>" onclick="return confirmDelete();" > Delete </a> </td> 
    </tr>
      <% count = count + 1 %>
  <%end%>
  </table>
</div>
<% end %>

<form id='newtestform' method='GET'>
  <table class="centered" style="width:60%;">
    <caption style="padding-bottom:20px;"> <h3>Take a new test</h3> </caption>
    <tr>
     <th style="text-align:left;width:50%;">Pick exam</th>
     <td style="padding-left:20px;">
        <select id="exam_drop_down" name="exam_id">
          <% @exams.each do |e| %>
            <div class="lbl">  </div><option value=<%= e.id %> ><%=e.exam_name%></option>
          <%end%>
        </select>
     </td>
  </tr>
  <tr>
    <th style="text-align:left;">
      Number of questions
    </th>
    <td style="padding-left:20px;">
      <select id='numofqs' name='numofqs'>
        <option>5</option>
        <option>10</option>
        <option>15</option>
        <option>20</option>
        <option>25</option>
      </select>
    </td>
  </tr>
  <tr id='test_item' >
    <th style="text-align:left;"> Test type </th> 
    <td style="padding-left:20px;"> <div id='test_type'></div></td>
  </tr>
</table>
<table id='units_tbl' class="centered" style="margin-top:10px;width:60%;">
  <tr>
    <th style="text-align:left;width:50%;">Pick unit</th>
    <td style="padding-left:20px;"><div id='units_ph'></div></td>
  </tr>
</table>
<div id='newtest_submit' class="centered" style="width:30%;padding-top:5%;padding-left:9%;"></div>
</form>

app/views/test_items/index.html.erb
<script type="text/javascript">
$("body").on({
    ajaxStart: function() { 
        $(this).addClass("loading"); 
    },
    ajaxStop: function() { 
        $(this).removeClass("loading"); 
    }    
});
function add_submit(TestName)
{
  var remote_func_name = 'new';
  switch(TestName)
  {
     case "Unit test": 
      $('test_item_name').value = 'unittest';
      break;
     case "Full test": 
      $('test_item_name').value = 'fulltest';
      break;
     case "Progressive test": 
      $('test_item_name').value = 'progressivetest';
      break;
     default:
      break; 
  };
  $('newtestform').writeAttribute('action',remote_func_name);
  var submit_attrs = { id: 'submittest' , value : 'Start  test', type: 'submit' };
  var submittest = new Element('input',submit_attrs);
  $(TestName).insert(submittest);
  return false;
}
function confirmDelete()
{
  var retval = false ;
  retval = confirm("Confirm delete!"); 
  return retval ;

};
function insertUnits(TestName,currentunit)
{
  if( undefined != currentunit )
  {
    $(TestName).insert(currentunit);
  }
  add_submit(TestName);
};
function test_selected(TestName)
 {
  if( undefined != $('currentunit') )
  {
    $('currentunit').remove();
  }
  if( undefined != $('submittest') )
  {
    $('submittest').remove();
  }
  var currentunit = undefined; 
  var functocall = "add_submit('"+TestName+"')";
  var retval = false;
  switch(TestName)
  {
     case "Unit test": 
      var currunit_attrs = { id : 'currentunit' };
      var currentunit = new Element('span',currunit_attrs);
      new Ajax.Updater('currentunit','/unit/indexdd',{asynchronous:true,method:'get',oncomplete:eval("insertUnits")("Unit test",currentunit)});
      break;
    case "Full test":
      numqs = $('numofqs').value
      $('Fulltest_link').href = $('Fulltest_link').href + ';numofqs=' + numqs  
      retval = true;
      break; 
    case "Progressive test": 
      var currunit_attrs = { id : 'currentunit' };
      var currentunit = new Element('span',currunit_attrs);
      new Ajax.Updater('currentunit','/unit/indexnottaken',{asynchronous:true,method:'get',oncomplete:eval("insertUnits")("Progressive test",currentunit)});
      break;
     default:
      break; 
  };
  return retval;
 };
</script>
<% even = 2 %>
<%if  %>
<%else %>
<form id='newtestform' method='GET'>
<div id="TestListContent" class="centered">
  <h1>Choose a test</h1>
  <div class="centered" style="padding-top:1px;padding-bottom:1px;">
  <% if @unfinished.length > 0 %> 
  <b>Restart previous test</b> 
  <br />
  <div id="UnsavedTests">
  <% count = 1 %>
  <% @unfinished.each do |t| %>
    <% testtype = TestType.where( :id => t.test_type_id ).first.name %>
      <div id="<%=t%>" class=<% if count%2 == 0 %>  "even testitem" <% else %> "odd testitem" <% end %> >
      <% tid = t.id %>
      <%= testtype  %> started at <%= t.created_on %> 
      <a href="restart?id=<%=tid%>" > Take again  </a> 
      <a href="delete?id=<%=tid%>" onclick="return confirmDelete();" > Delete </a> 
      </div>
      <% count = count + 1 %>
  <%end%>
  </div>
  <% end %>
  <b>Take new test</b>
  <br /> 
  <span style="padding-left:25px;padding-right:40px;margin-top:30px;">
    <b>Number of questions</b> 
    <select id='numofqs' name='numofqs'>
      <option>5</option>
      <option>10</option>
      <option>15</option>
      <option>20</option>
      <option>25</option>
    </select>
  </span>
  <input id='test_item_name' name='test_item_name' type='hidden'></input>
</div>
  <div id="TestList">
  <% if  @totaltests > 2  %>
         <%= link_to "Two free tests completed. Upgrade your account.",upgrade_path %>
         <% @AllTests.each do |t| %>
          <div id="<%=t%>" class=<% if even%2 == 0 %>  "even testitem" <% else %> "odd testitem" <% end %> >
            <% id = "#{t}_link" %>
            <div id=<%=id.gsub(/\s+/, "")%> href="#" ><%=t%></div>
          </div>
          <% even = even +1 %>
          <%end%>
     <%else%>
        <% @AllTests.each do |t| %>
          <div id="<%=t%>" class=<% if even%2 == 0 %>  "even testitem" <% else %> "odd testitem" <% end %> >
            <% id = "#{t}_link" %>
          <%if (t == "Full test") %>
            <a id=<%=id.gsub(/\s+/, "")%> href="new?test_item_name=full"  onclick="test_selected('<%=t%>')"><%=t%></a>
          <% else %>
             <a href="#"  onclick="test_selected('<%=t%>')"><%=t%></a>
          <% end %>
          </div>
          <% even = even +1 %>
          <%end%>
      <%end%>
  </div>
</div>
</form>

app/views/test_items/update.html.erb
<script type="text/javascript">
  function confirmCancel(){
    var retval = false;
    if ( confirm("Confirm cancel?") )
    {
      retval = true;
    }
    return retval;
  };
  function confirmSubmit(){
    var count = parseInt ( $('unanscount').value );
    var currCheck = ansCheckIndex();
    if(currCheck != -1 ){
      count = count -1;
    }
    var retval = false;
    if( count > 0 ){
       retval = confirm(" You have "+$('unanscount').value+" un-answered questions! Do you want to submit? ");
    }else{
       retval = confirm("Do you want to submit?");
    }
    return retval;
  }
  function ansCheckIndex(){
    retval = -1;
    buttons = $$('input.answer_buttons');
    for( var i = 0 ; i < buttons.length;i++)
    {
        if( buttons[i].checked){
          retval = i ;
        }
    }
    return retval+1;
  };
  function updateMath()
  {
    M.parseMath( $('currqform') );
  };
  function updateAndSubmit(pagenum){
    currpage = $('last_question_id').value;
    checkedindex = ansCheckIndex();
    new Ajax.Updater('currqform','update',
      {parameters:{page:pagenum,last_question_id:currpage,currchoice:checkedindex}
      ,method:'get',asynchronous:false,evalScripts:true,oncomplete:updateMath()});
    updateMath();
    return false;
  };
</script>
<form id='currqform' action='update'>
<div id="QuestionBox">
		<div id="QuestionNum">
			Current question number: <%= params[:page] %>
		</div>
    <%= render :partial => 'paginate' %>
    <div id='Question'>  
      <%= render :partial => 'currentquestion' %> 
    </div> 
  	<input type="hidden" id='last_question_id' value="<%= params[:page]  %>" />
  	<input type="hidden" id="unanscount"  value="<%= @unanscount %>" />
  	<% params.inspect %>
  	<% @question.inspect %>
	  <div align="center">
      <span>
        Submit test only after you have answered all the questions you can.
      </span>
      <p>
        <input type="submit" name="save" onclick='return confirmSubmit()' value="Submit test for evaluation"/>
        <input type="submit" name="cancel" onclick='return confirmCancel()' value="Cancel this test"/>
      </p>
	  </div>
</div>
</form>