config/routes.rb
Crackphysics::Application.routes.draw do

  get 'purchases/pay' => 'purchases#pay' , :as => 'purchases'
  get 'purchases/afterpay' => 'purchases#afterpay' , :as => 'after_purchases'
  get 'exams/index' => 'exam#index' , :as => 'examitems'
  get 'test_items/restart' => 'test_items#restart' , :as => 'restart_test_item'
  get 'test_items/delete' => 'test_items#delete' , :as => 'delete_test_item'
  get 'test_items/index' => 'test_items#index' , :as => 'testitems'
  get 'test_items/new' => 'test_items#new', :as => 'new_test_item'
  get 'test_items/get_testitem_details' => 'test_items#get_testitem_details', :as => 'get_testitme_details'
  get 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  put 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  get 'test_supervisor/loop' => 'test_supervisor#loop' , :as => 'testloop'
  get 'report/list_tests' => 'report#list_tests' , :as => 'showtests'
  get 'report/show_units_bar_chart' => 'report#show_units_bar_chart' , :as => 'showunitsbarchart'
  get 'report/show_tests_line_chart' => 'report#show_tests_line_chart' , :as => 'showtestslinechart'
  get 'report/print_test' => 'report#print_test' , :as => 'printtestpdf'
  get 'question_statements/showf' => 'question_statements#showf' , :as => 'getquestion'
  get 'test_factory/create_unit_test' => 'test_factory#create_unit_test', :as => 'createunittest' 
  get 'unit/index' => 'unit#index' , :as => 'unititems'
  get 'unit/indexdd' => 'unit#indexdd', :as => 'unitslist' 
  get 'unit/indexnottaken' => 'unit#indexnottaken', :as => 'unitsnottakenlist' 
  get 'unit/show/:id' => 'unit#show' , :as => 'unit'
  get 'user/welcome' => 'user#welcome', :as => 'welcome' 
  get 'main/start' => 'main#start', :as => 'home' 
  get 'how_to_upgrade' => 'main#how_to_upgrade', :as => 'upgrade' 
  post 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/show' => 'user#show', :as => 'usershow' 
  post 'user/signup' => 'user#signup', :as => 'usersignup' 
  post 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  get 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  put 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/logout' => 'user#logout', :as => 'userlogout' 
  get 'user/signup' => 'user#signup', :as => 'usersignup'
  get 'exam/get_test_types/:exam_id/:format' => 'exam#get_test_types'
  get 'exam/get_units/:exam_id/:format' => 'exam#get_units'
  get 'help' => 'main#show_help' , :as => 'help' 
  get 'feedback' => 'feedbacks#new', :as => 'feedback'
  post 'feedback/create' => 'feedbacks#create', :as => 'feedbackcreate'
  get 'subscription/index' => 'subscription#index', :as => 'subscriptionindex' 

  root :to => "main#start"

  mount PaypalIpn, :at => '/paypal_ipn' 
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  before_filter :login_required
  def list_tests
	  user_id = session['user'].id
	  @tests = TestItem.find(:all,:conditions => {:user_id => "#{user_id}",:status => "submit"},:order=> 'created_on' )
  end
  def show_tests_line_chart
	  user_id = session['user'].id
    tests_taken = TestItem.find_all_by_user_id(user_id,:order => :created_on)
    if tests_taken.length > 0 
      @linechartdata =[["Test no/Taken on","Correct/Total"]]
      count = 1
      tests_taken.each { |t|
        test_questions = TestQuestion.find_all_by_test_item_id(t.id)
        corrects = 0 
        test_questions.each{ |tq| corrects = corrects + 1 if  tq.current_choice == tq.correct_choice }
        total = test_questions.size
        correctratio = corrects.to_f / total ;
        @linechartdata << [ t.created_on.strftime("Test no #{count} on (%d/%m/%y) ")+total.to_s , correctratio ]
        count = count + 1
      }
    else 
      @linechartdata = nil
    end

  end 
  def show_units_bar_chart 
	  user_id = session['user'].id
    tests_taken = TestItem.find_all_by_user_id(user_id).select{|t| t.status == 'submit'}.collect { |t| t.id }
    logger.debug ">>>>>>>>>>>>>Tests taken",tests_taken
    if tests_taken.length > 0 
      test_questions = TestQuestion.find_all_by_test_item_id(tests_taken)
      is_correct = {}
      which_qsid = {}
      which_uid = {}
      @units = []
      test_questions.each{ |t| is_correct[t.id] = t.current_choice == t.correct_choice
      which_qsid[t.id] = t.question_statement_id }
      test_question_ids = test_questions.collect { |tq| tq.question_statement_id }.sort
      UnderlyingConcept.find_all_by_question_statement_id(test_question_ids).each{ |x| which_uid[x.question_statement_id]=x.unit_id
      @units<<Unit.find(x.unit_id)
      }
      #for each unit id find how many correct
      @unit_results = {}
      @units.each{ |u|
        one_result = {}
        one_result[:name] = u.name
        one_result[:corrects] = 0 
        one_result[:total] = 0 
        @unit_results[u.id] = one_result
      }
      test_questions.each{ |q|
        logger.debug @unit_results
        logger.debug q.inspect 
        uid = which_uid[ which_qsid[q.id] ]
        logger.debug "Uid is #{uid}" 
        result = @unit_results[uid]
        if result != nil
          result[:total] = result[:total] + 1
          if is_correct[q.id] then
            result[:corrects] = result[:corrects] + 1
          end
        end
      }
    @barchartdata =[["Unit","Correct","Wrong"]]
    @unit_results.each { |k,v| @barchartdata << [v[:name]+"-"+v[:total].to_s,v[:corrects],v[:total]-v[:corrects]] }
    else
      @units = nil 
   end
  end
  def print_test
    test_id = params[:test_id]
    @test = TestItem.find(test_id)
    @test_no = params[:test_no].to_i + 1
    @test_date = (@test.created_on).strftime("%d/%m/%y")
    @user = session['user']
    @q = TestQuestion.find_all_by_test_item_id(test_id)
    @qs = @q.collect{ |q| QuestionStatement.find_by_id(q.question_statement_id) }
  end
  def pdf
    @article = Test.find(@params["test_id"])
    #header
    @header = getheader(@params[:test_no],@params[:test_id])
    logger.info("header is "+@header.to_s)
    #rest of questions
    @questions = Test.find_all(@params[:test_id])
    generator = IO.popen("htmldoc -t pdf --path \".;http://#{@request.env["HTTP_HOST"]}\" --webpage -", "w+")
    generator.puts render("report/pdf")
    generator.close_write
    send_data(generator.read, :filename => "TestNumber#{@header['testno']}.pdf", :type => "application/pdf")
  end
  def pdf_old
	_pdf = PDF::Writer.new
	_pdf.select_font "Times-Roman"
	header = get_header(@params[:test_no],@params[:test_id])
	fs = _pdf.font_size
	_pdf.font_size = fs + 5
	_pdf.text header['name']
	_pdf.font_size = fs + 3
	_pdf.text("Test Number : "+header['testno'])
	_pdf.text("Taken on : "+header['startdate'])
	y0 = _pdf.y - 10
	x0 = 10
	_pdf.line(_pdf.absolute_left_margin,y0,_pdf.absolute_right_margin,y0).stroke
	_pdf.font_size = fs
	_pdf.y = y0 - 4
	questions = []
	answers = []
	correct = []
	choice = []
	testquestions = TestQuestion.find(:all, :conditions => ["test_id = #{@params[:test_id]}"])
	for testquestion in testquestions do
		q_stmt_id = testquestion.question_statement_id
		q_stmt = QuestionStatement.find(q_stmt_id)
		questions << q_stmt.statement
		choice << testquestion.choice
		correct << (testquestion.choice==4)
		seq = testquestion.answer_sequence
		a_stmts = [q_stmt.correct_ans_stmt, q_stmt.ans_stmt_1,q_stmt.ans_stmt_2,q_stmt.ans_stmt_3]
		answers << a_stmts
	end
	maintext = ""
	i = 0 
	for aq in questions do
		map_html(_pdf,"Q#{i+1}: "+aq)
		oldmargin = _pdf.left_margin
		_pdf.left_margin = oldmargin + 10
		if choice[i] == 1 and correct[i] 
			_pdf.fill_color  Color::RGB::Blue
			map_html(_pdf,"a) "+answers[i][0])
			_pdf.fill_color Color::RGB::Black
		elsif choice[i] == 1
			_pdf.fill_color  Color::RGB::Red
			map_html(_pdf,"a) "+answers[i][0])
			_pdf.fill_color Color::RGB::Black
		else
			map_html(_pdf,"a) "+answers[i][0])
		end
		if choice[i] == 2 and correct[i] 
			_pdf.fill_color  Color::RGB::Blue
			map_html(_pdf,"b) "+answers[i][1])
			_pdf.fill_color Color::RGB::Black
		elsif choice[i] == 2
			_pdf.fill_color  Color::RGB::Red
			map_html(_pdf,"b) "+answers[i][1])
			_pdf.fill_color Color::RGB::Black
		else
			map_html(_pdf,"b) "+answers[i][1])
		end
		if choice[i] == 3 and correct[i] 
			_pdf.fill_color  Color::RGB::Blue
			map_html(_pdf,"c) "+answers[i][2])
			_pdf.fill_color Color::RGB::Black
		elsif choice[i] == 3
			_pdf.fill_color  Color::RGB::Red
			map_html(_pdf,"c) "+answers[i][2])
			_pdf.fill_color Color::RGB::Black
		else
			map_html(_pdf,"c) "+answers[i][2])
		end
		if choice[i] == 4 and correct[i] 
			_pdf.fill_color  Color::RGB::Blue
			map_html(_pdf,"d) "+answers[i][3])
			_pdf.fill_color Color::RGB::Black
		elsif choice[i] == 4
			_pdf.fill_color  Color::RGB::Red
			map_html(_pdf,"d) "+answers[i][3])
			_pdf.fill_color Color::RGB::Black
		else
			map_html(_pdf,"d) "+answers[i][3])
		end
		_pdf.left_margin = oldmargin
		i = i+1
	end

	
	# from the test id and the user id get all the questions and their answers and if 
	# wrong print it in red
	send_data _pdf.render, :filename => "test#{@params[:test_no]}.pdf",
			    :type => "application/pdf"
  end
  def getheader(test_no,test_id)
  	 user = session['user']
	 header = {}
	 header['name'] = "#{user.lastname.swapcase}, #{user.firstname.swapcase}"
	 header['testno'] = test_no.to_s
	 test = Test.find(test_id)
	 header['date'] = (test.created_on).strftime("%d/%m/%y")
	 return header
  end
  def map_html(pdf,str)
	  indexf = str.index("<sup>")
	  unless indexf.nil?
		  indexb = str.rindex("</sup>")
		  pdf.text str[0..(indexf-1)]
		  width = pdf.text_width( str[0..(indexf-1)] ) + pdf.left_margin
		  suptxt = str[(indexf+5)..(indexb-1)]
		  resttext = str[(indexb+6)..str.length]
		  y0 = pdf.y
		  fs = pdf.font_size
		  pdf.font_size = fs - 3
		  pdf.y = pdf.y+5
		  pdf.add_text(width,pdf.y,suptxt)
		  width = width + pdf.text_width(suptxt)
		  pdf.font_size = fs
		  pdf.y = y0
		  pdf.add_text(width,pdf.y,resttext)
	  else
		  pdf.text str
	  end
  end
end

app/views/report/_question.html.erb
<% unattempted = (0 == q.current_choice) %>
<span class='qnum'>Question# <%= num+1%>.</span>
<div class='rptq'>
   <%= raw qs.statement %> <%= raw "<div class='unattempted'>(Unattempted)</div>" if( unattempted ) %> 
</div>
<div class='rptans'>
<table class='ansstmts'>
  <tr><th class='ansindex'></th><th class='ansstmt'></th><th class='anscheck'></th></tr>
  <% count = 0 %>
  <% q.inspect %>
  <% is_correct = (q.correct_choice == q.current_choice) %>
  <% for choice in q.answer_sequence  %>
    <% ans = qs.choices[choice-1] %>
    <% img_name = 'correct.png' if (is_correct and (count+1==q.correct_choice)) or (!is_correct and (count+1) == q.correct_choice) %> 
    <% img_name = 'incorrect.png' if ! is_correct and (count+1==q.current_choice) %>
    <% classname = 'even' if count % 2 == 0 %>
    <% classname = 'odd' if count % 2 != 0 %>
    <% classnameanstd = 'rightans' if (!is_correct or unattempted) and (count+1==q.correct_choice) %>
    <tr class='<%= classname %>' >
      <td><%= count+1 %>)</td>
      <td class='one_ans_stmt <%= classnameanstd%>'><%= raw ans %></td>
      <td><%= image_tag( img_name,:size => '20x20',:border=>'0') if img_name %></td>
    </tr>
    <% classnameanstd = ''  %>
    <% count = count + 1 %>
    <% img_name = nil %>
  <%end%>
</table>
</div>

app/views/report/_submenu.html.erb
<% chartlinks = { :units_bar_chart => ["Units performance",showunitsbarchart_path],:tests_line_chart => ["Progress over time",showtestslinechart_path] } %>
<% links = [] 
chartlinks.collect { |k,v| if k == chartname then
   links << v[0] 
  else 
    links << (link_to v[0],v[1])
   end
} %>
<div id='AnalyticSecondBar'>
<%links.each { |l| %>
<%=  l.to_s %>
<%}%>
</div>

app/views/report/_testslinechart.html.erb
<% content_for :head do %>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
 <%= raw data.collect{|x| x.to_s}.join(",\n") %>
        ]);

        var options = {
          title: 'Performance over time',
          hAxis: {title: 'Test #/Taken on/Total attempted', titleTextStyle: {color: '#FF0000'}, slantedText: true, slantedTextAngle: 22  },
          colors: ['orange'],
          backgroundColor: 'beige'
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
    <% end %>
<div id="TestChartOverTime">
<div id="chart_div" style="width: 900px; height: 500px;"></div>
</div>

app/views/report/_unitsbarchart.html.erb
<% content_for :head do %>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
   google.load("visualization", "1", {packages:["corechart"]});
   google.setOnLoadCallback(drawChart);
   function drawChart() {
    var data = google.visualization.arrayToDataTable([
<%= raw data.collect{|x| x.to_s}.join(",\n") %>
    ]);

    var options = {
     title: 'Unitwise performance',
     hAxis: {title: 'Unit name-Total Questions attempted', titleTextStyle: {color: 'red'}},
          backgroundColor: 'beige',
          colors: ['green','red'] 
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    chart.draw(data, options);
   }
  </script>
<% end %>
<div id="BarChartUnitWise">
<div id="chart_div" style="width: 900px; height: 500px;"></div>
</div>

app/views/report/show_tests_line_chart.html.erb
<% if @units != nil and @units.length > 0  %>
<div id='UnitsAttemptedAnal'>
<%= render partial: 'submenu', :locals => {:chartname=>:tests_line_chart} %> 
<%= render partial: 'testslinechart',:locals =>{:data=>@linechartdata} %>
</div>
<% else %>
<div class='errorbox'>You have not taken any tests yet.</div>
<%end%>

app/views/report/show_units_bar_chart.html.erb
<% if @units != nil and @units.length > 0 %>
<div id='UnitsAttemptedAnal'>
<%= render partial: 'submenu', :locals => {:chartname=>:units_bar_chart} %> 
<%= render partial: 'unitsbarchart',:locals =>{:data=>@barchartdata} %>
</div>
<% else %>
<div class='errorbox'>You have not taken any tests yet.</div>
<%end%>