config/routes.rb
Crackphysics::Application.routes.draw do

  get 'purchases/pay' => 'purchases#pay' , :as => 'purchases'
  get 'purchases/afterpay' => 'purchases#afterpay' , :as => 'after_purchases'
  get 'exams/index' => 'exam#index' , :as => 'examitems'
  get 'test_items/restart' => 'test_items#restart' , :as => 'restart_test_item'
  get 'test_items/delete' => 'test_items#delete' , :as => 'delete_test_item'
  get 'test_items/index' => 'test_items#index' , :as => 'testitems'
  get 'test_items/new' => 'test_items#new', :as => 'new_test_item'
  get 'test_items/get_testitem_details' => 'test_items#get_testitem_details', :as => 'get_testitme_details'
  get 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  put 'test_items/update' => 'test_items#update', :as => 'update_test_item'
  get 'test_supervisor/loop' => 'test_supervisor#loop' , :as => 'testloop'
  get 'report/list_tests' => 'report#list_tests' , :as => 'showtests'
  get 'report/show_units_bar_chart' => 'report#show_units_bar_chart' , :as => 'showunitsbarchart'
  get 'report/show_tests_line_chart' => 'report#show_tests_line_chart' , :as => 'showtestslinechart'
  get 'report/print_test' => 'report#print_test' , :as => 'printtestpdf'
  get 'question_statements/showf' => 'question_statements#showf' , :as => 'getquestion'
  get 'test_factory/create_unit_test' => 'test_factory#create_unit_test', :as => 'createunittest' 
  get 'unit/index' => 'unit#index' , :as => 'unititems'
  get 'unit/indexdd' => 'unit#indexdd', :as => 'unitslist' 
  get 'unit/indexnottaken' => 'unit#indexnottaken', :as => 'unitsnottakenlist' 
  get 'unit/show/:id' => 'unit#show' , :as => 'unit'
  get 'user/welcome' => 'user#welcome', :as => 'welcome' 
  get 'main/start' => 'main#start', :as => 'home' 
  get 'how_to_upgrade' => 'main#how_to_upgrade', :as => 'upgrade' 
  post 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/login' => 'user#login', :as => 'userlogin' 
  get 'user/show' => 'user#show', :as => 'usershow' 
  post 'user/signup' => 'user#signup', :as => 'usersignup' 
  post 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  get 'user/forgot_password' => 'user#forgot_password', :as => 'userforgot_password' 
  put 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/change_password' => 'user#change_password', :as => 'userchange_password' 
  get 'user/logout' => 'user#logout', :as => 'userlogout' 
  get 'user/signup' => 'user#signup', :as => 'usersignup'
  get 'exam/get_test_types/:exam_id/:format' => 'exam#get_test_types'
  get 'exam/get_units/:exam_id/:format' => 'exam#get_units'
  get 'help' => 'main#show_help' , :as => 'help' 
  get 'feedback' => 'feedbacks#new', :as => 'feedback'
  post 'feedback/create' => 'feedbacks#create', :as => 'feedbackcreate'
  get 'subscription/index' => 'subscription#index', :as => 'subscriptionindex' 

  root :to => "main#start"

  mount PaypalIpn, :at => '/paypal_ipn' 
end

app/views/layouts/_top_nav_bar.html.erb
<div id="TopNavBar" class='topnavbar'>
<% if (controller.controller_name == 'test_items' && controller.action_name == 'update') then %>
  <div id="TestBar">
   Test in progress! Please press "Submit test" button when finished. move it to the tob bar
  </div>
<%else%>
  <% unless (controller.controller_name == 'main' && controller.action_name == 'start')  %>
  <%= link_to "[Home]", :controller=>'main', :action=>'start' %>
  <% end %>
  <% unless session[:user] %>
    <% unless (controller.controller_name == 'user' && controller.action_name == 'login')  %>
      <%= link_to "[Sign in]", userlogin_path %>
    <%end%>
    <% unless (controller.controller_name == 'user' && controller.action_name == 'signup')  %>
      <%= link_to "[Register]", :controller => 'user', :action=> 'signup' %>
    <%end%>
  <% end %>
  <% if session[:user] %>
  <%= link_to "[Take test]", :controller=>'test_items',:action=>'new' unless (controller.controller_name == 'test_items' and controller.action_name == 'index')%>
  <% if (controller.controller_name != 'report' or controller.action_name != 'list_tests' )  %>
    <%= link_to "[Results]", :controller=>'report',:action=>'list_tests'%>
  <% end %>
  <% if (controller.controller_name != 'report' or controller.action_name == 'list_tests' )  %>
    <%= link_to "[Analytics]", showunitsbarchart_path%>
  <%end%>
  <%= link_to "[Account]", usershow_path %>
  <% end %>
  <% if session[:user] and User.find_by_id(session[:user].id).role == '999' %>
  <%= link_to "[Verify]", unititems_path %>
  <% end %>
  <%= link_to "[Help!]", :controller=>'main',:action=>'show_help'  %>
  <%= link_to "[Feedback]", feedback_path %>
  <span id='signout_top_nav_link'><%= link_to "[Sign out]", :controller=>'user',:action=>'logout' %></span>
  <% end %>
  <% if session[:user] %>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crackphysics.com -- Intelligent way to study</title>
  <script src="http://www.google-analytics.com/urchin.js" type="text/javascript" />
  <script type="text/javascript">
    _uacct = "UA-249687-2";
    urchinTracker();
  </script>
  <%  cname= controller.controller_name %>
  <%  aname =  controller.action_name  %> 
  <%= stylesheet_link_tag :all %>
  <% if cname == 'test_items' && (aname == 'index' or aname == 'get_testitem_details') %> 
    <%= javascript_include_tag :defaults %>
  <% end %>
  <% if (cname == 'test_items' && aname == 'update') or ( cname == 'report' && aname == 'print_test') or ( cname == 'unit' && aname == 'show') %> 
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "jquery-1.4.3" %>
    <%= javascript_include_tag "jscurry-0.2.0" %>
    <%= javascript_include_tag "jqmath-0.2.0" %>
    <%= javascript_include_tag "jqmath-etc-0.2.0.min" %>
  <% end %>
  <%if (cname  == 'report' ) %> 
    <%= yield :head %>
  <%end%>
  <% if (cname == 'user') %> 
    <%= javascript_include_tag :defaults %>
  <% end %>
  <meta name="keywords" content="AIEEE,Physics,Online,Tests,Test series,India" />
  <meta name="description" content="Online test series to prepare for entrance exams in India." />
  <%= csrf_meta_tag %>
</head>
<body>
<div id="BannerBox">
	<div id="BannerLine1"> Crackphysics.com </div>
	<div id="BannerLine2">An online physics tutor and tester.</div>
  <br />
  <br />
  <div id=BannerLine3> Simple, smart and cost effective way to prepare for physics entrance tests.</div>
</div>
<div>
<%= render :partial => "layouts/top_nav_bar" %>
<div id="MainBox">
<%= yield %>
</div>
<div id="CopyBox">
	(c) 2005- <%= Time.now.strftime("%Y") %> http://www.crackphysics.com
</div>
</body>
</html>

app/views/layouts/report.html.erb
<%= render :template => 'layouts/application' %>